# Generated by Django 5.1.6 on 2025-06-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='user_type',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('admin', 'Admin'), ('staff', 'Staff')], default='passenger', max_length=10),
        ),
    ]
