# Generated by Django 5.1.5 on 2025-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
