# Generated by Django 5.1.5 on 2025-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='expertise',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='languages',
            field=models.TextField(default='[]'),
        ),
    ]
