# Generated by Django 5.1.5 on 2025-05-11 12:32

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_staff_options_remove_staff_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=complaints.models.staff_avatar_path),
        ),
    ]
