# Generated by Django 5.1.5 on 2025-05-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_staff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='communication_preferences',
            field=models.TextField(blank=True, default='["Chat"]', null=True),
        ),
    ]
