# Generated by Django 5.1.5 on 2025-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_created_at_complaint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
