# Generated by Django 5.1.6 on 2025-06-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_improve_complaint_tracking'),
        ('complaints', '0011_complaint_resolution_notes_complaint_resolved_at_and_more'),
    ]

    operations = [
    ]
