# Generated by Django 5.1.6 on 2025-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_merge_20250623_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='first_response_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='source',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
