# Generated by Django 5.1.6 on 2025-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_alter_complaint_priority_alter_complaint_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationresult',
            name='complaint',
        ),
        migrations.DeleteModel(
            name='QuickSolution',
        ),
        migrations.RemoveField(
            model_name='supportsession',
            name='agent',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClassificationResult',
        ),
        migrations.DeleteModel(
            name='SupportSession',
        ),
    ]
