# Generated by Django 5.1.6 on 2025-08-03 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_remove_classificationresult_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('solution', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('resolution_time', models.CharField(max_length=50)),
                ('success_rate', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Quick Solutions',
            },
        ),
    ]
